############################################################
#
# web访问端口号
#
############################################################
server:
  port: 7777
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
#      国际化配置
  messages:
    basename: i18n/messages
    encoding: utf-8
    cache-duration: 1
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.jhmarryme.demo.pojo.model          # 所有POJO类所在包路径
#  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.jhmarryme.demo.common.mybatis.BaseMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
#pagehelper:
#  helperDialect: mysql
#  supportMethodsArguments: true

cola:
  exception:
    enable: true
  i18n:
    enable: true
    interceptor: true

spring:
  profiles:
    active: dev